name: Continuous Integration

on:
  push:
    paths:
      - '**.f90'
      - '**.fpp'
      - '**.py'
      - '**.yml'
      - 'mfc.sh'
      - 'golden.txt'
      - 'CMakeLists.txt'

  pull_request:

  workflow_dispatch:

jobs:
  tests:
    name: Test Suite
    strategy:
      matrix:
        include:
          - os:  ubuntu-latest
            gcc: 11
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone
        uses: actions/checkout@v3
